version: "3.3"
services:
  nodebb:
    image: elestio/nodebb:latest
    # command: ["sh","entrypoint.sh"]
    restart: always
    environment:
      URL: "https://nodebbsdsd-u353.vm.elestio.app"
      DATABASE: "redis"
      DB_NAME: "0"
      DB_HOST: "redis"
      DB_PORT: "8443"
    volumes:
      # - ./data/nodebb:/data
      - ./nodebb-files:/usr/src/app/public/uploads
      # - ./nodebb-config/config.json:/usr/src/app/config.json
      - ./entrypoint.sh:/usr/src/app/entrypoint.sh
    ports:
      - "172.17.0.1:4956:4567"

  redis:
    image: redis
    restart: always
    volumes:
      - ./nodebb-data:/data
    ports:
      - "172.17.0.1:5069:6379"
